/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pfe;

import Connexion.Connexion;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SirineA
 */
public class Gestion_Admin extends javax.swing.JFrame {

    /**
     * Creates new form Gestion_Admin
     */
     //creation instance de classe "Connector" connexion
   Connexion cnn=new Connexion();
   //transferer les requetes avec la base
     Statement stm;
     //recuperer les reponse de base
     ResultSet Rs;
     DefaultTableModel model=new DefaultTableModel();
    public Gestion_Admin() {
        initComponents();
         model.addColumn("Id");
         model.addColumn("Nom");
         model.addColumn("Prenom");
            model.addColumn("Password");
         model.addColumn("Email");
      
        
          try{
             stm=cnn.ObtenirConnexion().createStatement();
             ResultSet Rs=stm.executeQuery("Select * from user");
             while (Rs.next()){
                 model.addRow(new Object[]{Rs.getString("id"),Rs.getString("nom"),Rs.getString("prenom"),Rs.getString("password"),Rs.getString("email")});
             }
         }catch(Exception e) {System.err.println(e);}
table.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 460));
        setMinimumSize(new java.awt.Dimension(800, 460));
        setPreferredSize(new java.awt.Dimension(800, 460));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 460));
        getContentPane().setLayout(null);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Id:");
        jLabel7.setEnabled(false);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 90, 20, 17);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Prenom:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 200, 67, 17);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Nom:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 140, 41, 17);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Email:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 310, 46, 17);

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Password:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 260, 84, 17);

        jTextField2.setEnabled(false);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(150, 90, 140, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(150, 140, 140, 30);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(150, 190, 140, 30);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(150, 250, 140, 30);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(150, 300, 140, 30);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/ooo.jpg"))); // NOI18N
        jButton2.setText("Supprimer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(470, 290, 130, 40);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/edit.png"))); // NOI18N
        jButton3.setText("Modifier");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(630, 290, 130, 40);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/plus.png"))); // NOI18N
        jButton4.setText("Ajouter");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(310, 290, 130, 40);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nom", "Prenom", "Password", "Email"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(310, 90, 480, 180);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Gestion Des Utilisateurs");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 20, 340, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/undo.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 40, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/01_Fils_electriques_2.jpg"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(32767, 32767));
        jLabel3.setMinimumSize(new java.awt.Dimension(540, 420));
        jLabel3.setPreferredSize(new java.awt.Dimension(900, 850));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 900, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try {
           if (JOptionPane.showConfirmDialog(null,"Vous etes sur de supprimer ce admin !","supprimer admin",JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION)
       if (jTextField2.getText().length() !=0)
           { stm.executeUpdate("Delete from user where id = "+jTextField2.getText());afficher();
       }  else {JOptionPane.showMessageDialog(null, "Veuillez SVP Remplire Le Champ email!");}
           
       }  catch (Exception e) {JOptionPane.showMessageDialog(null, "erreur de supprimer \n"+e.getMessage());} 
       
       
      jTextField2.setText("");
      jTextField3.setText("");
      jTextField4.setText("");
      jTextField5.setText("");
      jTextField6.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        try {
    int i=table.getSelectedRow();deplace(i);
}
catch (Exception e){JOptionPane.showMessageDialog(null, "erreur de deplacement"+e.getLocalizedMessage());}
    }//GEN-LAST:event_tableMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
     
      String nom=jTextField3.getText();
      String prenom=jTextField4.getText();
      String email=jTextField6.getText();
      String password=jTextField5.getText();
      String Id=jTextField2.getText();
     
    
        String sql="select email from user where email = '"+email+"'";    
        ResultSet resultat = stm.executeQuery(sql);
          int count=0;
        //ceci pour verisier l'existance d'email 
    	 while(resultat.next()){
             count=count+1;}
     
         
            if(count==1){
                JOptionPane.showMessageDialog(null,"email Exist déjà");
                 jTextField6.setText("");
            }
            
        else{
    String requete="insert into user(nom,prenom,password,email)VALUES('"+nom+"','"+prenom+"','"+password+"','"+email+"')";
                
        //executeUpdate :requete insert et requete update.....executeQuery: requete select
        stm.executeUpdate(requete);
        JOptionPane.showMessageDialog(null, "Admin est bien ajouter");
    
    }} catch (Exception ex){JOptionPane.showMessageDialog(null,ex.getMessage());}
    afficher();
      jTextField6.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try {
       int row =table.getSelectedRow();
        int col = 0; // ID is the first Column
       if (JOptionPane.showConfirmDialog(null,"confirmer la modification","modification",JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION)
       {
       stm.executeUpdate("UPDATE user SET nom='"+jTextField3.getText()+"',prenom='"+jTextField4.getText()+"',password='"+jTextField5.getText()+"',email='"+jTextField6.getText()+
               "' WHERE id= "+jTextField2.getText());
   }
   }catch (Exception e){JOptionPane.showMessageDialog(null,"erreur de modifier !!!!"+e.getMessage());
   System.err.println(e);}
    afficher();
      jTextField2.setText("");
      jTextField3.setText("");
      jTextField4.setText("");
      jTextField5.setText("");
      jTextField6.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        Choix Sirine =new Choix();
            Sirine.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void deplace (int i){
     jTextField2.setText(model.getValueAt(i,0).toString());
    jTextField3.setText(model.getValueAt(i,1).toString());
    jTextField4.setText(model.getValueAt(i,2).toString());
    jTextField5.setText(model.getValueAt(i,3).toString());
    jTextField6.setText(model.getValueAt(i,4).toString());
  
try {}catch( Exception e){System.err.println(e);
JOptionPane.showMessageDialog(null,"erreur de deplacement"+e.getLocalizedMessage());
}}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion_Admin().setVisible(true);
            }
        });
    }
    private void afficher() {
        try {
    model.setRowCount(0);
stm=cnn.ObtenirConnexion().createStatement();
ResultSet Rs=stm.executeQuery("Select * from user");
while(Rs.next()){
model.addRow(new Object[]{Rs.getString("id"),Rs.getString("nom"),Rs.getString("prenom"),Rs.getString("password"),
    Rs.getString("email")});

}
}catch(Exception e){System.err.println(e);}

table.setModel(model);
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
