/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pfe;
import Connexion.Connexion;
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.*;
import java.sql.SQLException;
import javax.swing.JFrame;


/**
 *
 * @author asus
 */
public class Login extends javax.swing.JFrame {
    public Calcul_Tour login2;
 Connexion cn=new Connexion();
    public Statement st;
     public Login() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Pass1 = new javax.swing.JPasswordField();
        jEmail = new javax.swing.JLabel();
        jPassword = new javax.swing.JLabel();
        jButton1Login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        User1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(68, 108, 179));
        setMaximumSize(new java.awt.Dimension(800, 460));
        setMinimumSize(new java.awt.Dimension(800, 460));
        setPreferredSize(new java.awt.Dimension(800, 460));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 460));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 460));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 460));
        jPanel1.setLayout(null);

        Pass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pass1ActionPerformed(evt);
            }
        });
        jPanel1.add(Pass1);
        Pass1.setBounds(370, 180, 170, 34);

        jEmail.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jEmail.setText("Nom:");
        jPanel1.add(jEmail);
        jEmail.setBounds(172, 130, 180, 34);

        jPassword.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPassword.setText("Password:");
        jPanel1.add(jPassword);
        jPassword.setBounds(172, 190, 150, 28);

        jButton1Login.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1Login.setForeground(new java.awt.Color(0, 0, 204));
        jButton1Login.setText("Login");
        jButton1Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1LoginMouseClicked(evt);
            }
        });
        jButton1Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1LoginActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1Login);
        jButton1Login.setBounds(370, 240, 170, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/login1.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(580, 120, 200, 200);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/undo.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 11, 46, 22);

        User1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User1ActionPerformed(evt);
            }
        });
        jPanel1.add(User1);
        User1.setBounds(370, 130, 170, 33);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/istockphoto-669377248-612x612.jpg"))); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(600, 400));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 140, 800, 330);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        Acceuil Sirine =new Acceuil();
        Sirine.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1LoginActionPerformed
        try{
            //Recuperer les valeurs saisi dans formulaire
            String password=Pass1.getText().toString();
            String email=User1.getText().toString();

            String sql="select password,email from user where password = '"+password+"'and email = '"+email+"'";
            st=cn.ObtenirConnexion().createStatement();
            ResultSet rss=st.executeQuery(sql);

            //TEST SI LE USER EST EXISTE OU NON SELON LE VARIABLE COUNT
            int count=0;
            while(rss.next())
            {
                count=count+1;
            }
            if(count==1){
                JOptionPane.showMessageDialog(null, "Welcome User !!!");
                //ceci pour transferer a la page d'accueil
                Calcul_Tour  Sirine =new Calcul_Tour();
                Sirine.setVisible(true);
                this.dispose();
            }
            else
            if(count>1){
                JOptionPane.showMessageDialog(null, "Duplicate Acces!!! Acces denied");
                Pass1.setText("");
                User1.setText("");

            }

            else
            {
                JOptionPane.showMessageDialog(null, "User Not Found");
                Pass1.setText("");
                User1.setText("");

            }

        }
//        catch (Exception e){
//            JOptionPane.showMessageDialog(null, "No login");
//
//        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_jButton1LoginActionPerformed

    private void jButton1LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1LoginMouseClicked
        // TODO add your handling code here:
        Calcul_Tour Sirine =new Calcul_Tour();
        Sirine.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton1LoginMouseClicked

    private void User1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_User1ActionPerformed

    private void Pass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pass1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Pass1;
    private javax.swing.JTextField User1;
    private javax.swing.JButton jButton1Login;
    private javax.swing.JLabel jEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jPassword;
    // End of variables declaration//GEN-END:variables
}
